### ISSUE TITLE
Upgrade bootstrap

### ISSUE THREAD

**Issue by Tjoosten** [ApiGen/ThemeBootstrap#1]
Upgrade bootstrap to the latest version.

**Comment by TomasVotruba** [comment]
Could you send PR?

**Comment by Tjoosten** [comment]
not familiar with .lattee files

**Comment by TomasVotruba** [comment]
What exactly do you want to upgrade?

**Comment by Tjoosten** [comment]
the css mostly because you are using the v2 version

**Comment by TomasVotruba** [comment]
I see. I'd wait for this PR first: https://github.com/apigen/ApiGen/pull/504, this is now used by apigen master yet.

**Comment by TomasVotruba** [comment]
@Tjoosten https://github.com/apigen/ApiGen/pull/504 is merged, so we can continue.

Could you prepare PR for bootstrap v3?

**Comment by TomasVotruba** [comment]
Ping @Tjoosten

**Comment by Tjoosten** [comment]
?

**Comment by TomasVotruba** [comment]
See my previous comment. Would you prepare PR for bootstrap v3?

I'm thinking of dropping this theme and let it up to end users. I do not personally use it, don't have time to upgrade it and there is no maintainer yet.

**Comment by TomasVotruba** [comment]
@olvlvl Hey, just wondering if you're still using ApiGen with this theme.

**Comment by olvlvl** [comment]
Hi Tomas, yes I'm still using this theme. I need to evaluate the time it would require for me to update it to Bootstrap v3.

**Comment by TomasVotruba** [comment]
@olvlvl I see, just take your time. Thanks for fast reply.

**Comment by olvlvl** [comment]
Done: https://github.com/ApiGen/theme-bootstrap/pull/3

**Comment by TomasVotruba** [comment]
Closed via #3
