### ISSUE TITLE
Colors too light?

### ISSUE THREAD

**Issue by yoosefi** [ApiGen/ThemeBootstrap#10]
I'm having difficulty seeing the colored text in the generated docs, they are extremely light. Internal links for example are a couple shades lighter than external links.

Here are my docs:
http://hfw.github.io/h/current/class-H.H.html

Is there a specific palette you use in case I want to darken them and send a pull request?

**Comment by olvlvl** [comment]
The palette is the basic Bootstrap palette. You can try to customize it using their tool:

http://getbootstrap.com/customize/

**Comment by yoosefi** [comment]
is there a way to add custom css as a CLI option without having to fork the theme?

**Comment by yoosefi** [comment]
this for example would be nice https://bootswatch.com/cosmo/

**Comment by yoosefi** [comment]
@olvlvl see https://github.com/ApiGen/ThemeBootstrap/blob/master/src/resources/style.css

the colors are hard coded and aren't a part of bootstrap.css

**Comment by TomasVotruba** [comment]
> is there a way to add custom css as a CLI option without having to fork the theme?

This would be probably over engineering.

Do you have some specific proposal?

**Comment by olvlvl** [comment]
@yoosefi Yes some colors are defined in the CSS, but they are not overriding bootstrap's.

**Comment by yoosefi** [comment]
@olvlvl :+1:
