### ISSUE TITLE
How can I set/get custom configs from apigen.neon file?

### ISSUE THREAD

**Issue by nelson6e65** [ApiGen/ThemeBootstrap#11]
I got an error when I try to set another value:

```
[nmartell@localhost php_nml]$ apigen generate

The option "transifexLive" does not exist. Known options are: "accessLevels",
 "annotationGroups", "baseUrl", "charset", "config", "debug", "deprecated", "destination",
 "download", "exclude", "extensions", "googleAnalytics", "googleCseId", "groups",
 "internal", "main", "noSourceCode", "php", "skipDocPath", "source", "sourceCode",
 "template", "templateConfig", "templateTheme", "title", "todo", "tree", "visibilityLevels".
```

https://github.com/ApiGen/ApiGen/issues/626

Specifically, I need to add Transifex Live (translation functionality), to use in template like this:
https://github.com/nelson6e65/ThemeBootstrap/commit/bc419896019659f894e3da48a9471ed4f6d303a2

**Comment by jadb** [comment]
Sorry for the late reply. Don't want to close this unanswered.

Options are passed using their lowercased dash_-erized_ version:
- `accessLevels` would be `--access-levels`
- `charset` would be `--charset`

Hoping this answers your question.

**Comment by nelson6e65** [comment]
Well... No, I just want to declare another variable/option to use in template. In this case, define and set `transifexLive` and, for example, use it like `googleAnalytics` in the commit I referenced ([@layout.latte: L15-L37](https://github.com/nelson6e65/ThemeBootstrap/blob/bc419896019659f894e3da48a9471ed4f6d303a2/src/%40layout.latte#L15-L37)) to support [Transifex Live features](https://www.transifex.com/lp/transifex-live/).

**Comment by jadb** [comment]
@nelson6e65 for that, you will need to edit the template itself I am afraid. ApiGen doesn't inject undefined variables into any theme.

**Comment by nelson6e65** [comment]
:fearful:
