### ISSUE TITLE
Option for Google Analytics Universal tracking?

### ISSUE THREAD

**Issue by jtsternberg** [ApiGen/ThemeBootstrap#13]
Related: https://github.com/ApiGen/ApiGen/issues/592

That one was closed, but I still don't see any option for universal tracking: https://github.com/ApiGen/ThemeBootstrap/blob/dd4a5321d430ffb1867125479715bf576811dc37/src/%40layout.latte

Am I missing something?

**Comment by jadb** [comment]
Sorry for the late reply.

@jtsternberg have you tried since? A new phar was released since.

**Comment by jtsternberg** [comment]
@jadb This is likely a dumb question, but what do you mean?

**Comment by jtsternberg** [comment]
And no, there is no version of the template which contains the updated UT code. Current template: https://github.com/ApiGen/ThemeBootstrap/blob/master/src/%40layout.latte

Related: https://github.com/ApiGen/ThemeBootstrap/pull/9

**Comment by jadb** [comment]
Sorry for the extremely late reply. Trying to catch up.

~~Excuse my _dumb_ question as maybe I am mixing up GA codes. Isn't [this](https://github.com/ApiGen/ThemeBootstrap/blob/dd4a5321d430ffb1867125479715bf576811dc37/src/%40layout.latte#L15-L25) for tracking?~~

I see what you mean now in the linked PR. Should have read that first.

**Comment by jadb** [comment]
Closing. Fixed in #21.

**Comment by jtsternberg** [comment]
:thumbsup:

**Comment by jtsternberg** [comment]
What's the best way to update my version to the latest?
