### ISSUE TITLE
Need admin permission to maintain

### ISSUE THREAD

**Issue by jankal** [ApiGen/ThemeBootstrap#27]
@kukulich I don't have any admin permission on this to set @olvlvl as a collaborator for letting him push his changes on this theme by himself.

You may jsut add him / give him permission.

**Comment by kukulich** [comment]
I added @olvlvl.

**Comment by olvlvl** [comment]
@kukulich I don't think it worked, I can't merge my own changes, and I don't have access to the admin panel.

**Comment by olvlvl** [comment]
Never mind my message guys, I didn't accept the invitation yet 😊 Thanks for that!

**Comment by jankal** [comment]
@olvlvl Do you now have the access needed for [#26](https://github.com/ApiGen/ThemeBootstrap/pull/26#issuecomment-286056979)?

**Comment by olvlvl** [comment]
@jankal Yes, I do. Thanks.
